// One-time seed data for โรงเรียนอนุบาลอุบลราชธานี: grade levels + teacher roster.
// Used by the admin "นำเข้าข้อมูลสายชั้น & ครู" import button. gradeLevel on each
// teacher matches a grade level `name` so the submit form can filter by สายชั้น.

export interface SeedTeacher {
  fullName: string;
  position: string;
  gradeLevel: string;
}

export const SEED_GRADE_LEVELS: { name: string; order: number }[] = [
  { name: "ผู้บริหาร", order: 1 },
  { name: "อ.1", order: 2 },
  { name: "อ.2", order: 3 },
  { name: "อ.3", order: 4 },
  { name: "ป.1", order: 5 },
  { name: "ป.2", order: 6 },
  { name: "ป.3", order: 7 },
  { name: "ป.4", order: 8 },
  { name: "ป.5", order: 9 },
  { name: "ป.6", order: 10 },
  { name: "ห้องเรียนพิเศษ AP", order: 11 },
  { name: "English Program (EP)", order: 12 },
];

export const SEED_TEACHERS: SeedTeacher[] = [
  // 1. ผู้บริหารสถานศึกษา
  { fullName: "นายอรรถพร สำเภา", position: "ผู้อำนวยการโรงเรียน", gradeLevel: "ผู้บริหาร" },
  { fullName: "นางอัมรา บุญมา", position: "รองผู้อำนวยการโรงเรียน", gradeLevel: "ผู้บริหาร" },
  { fullName: "นายอลงกรณ์ โหราย์", position: "รองผู้อำนวยการโรงเรียน", gradeLevel: "ผู้บริหาร" },
  { fullName: "นางวิมลลักษณ์ ตีระมาศวณิช", position: "รองผู้อำนวยการโรงเรียน", gradeLevel: "ผู้บริหาร" },
  { fullName: "นางปราณี สานนท์", position: "รองผู้อำนวยการโรงเรียน", gradeLevel: "ผู้บริหาร" },

  // 2. อนุบาลปีที่ 1
  { fullName: "นางวงเพชร การุณย์", position: "ครูชำนาญการพิเศษ", gradeLevel: "อ.1" },
  { fullName: "นายวรพงษ์ ครุฑแสน", position: "ครู", gradeLevel: "อ.1" },
  { fullName: "นางสาววิยะดา สาระจันทร์", position: "ครูอัตราจ้าง", gradeLevel: "อ.1" },
  { fullName: "นางสาวพรศิริรักษ์ แก้วพิทักษ์", position: "ครูชำนาญการ", gradeLevel: "อ.1" },
  { fullName: "นางสาวเบญญา บุปผาพรหม", position: "ครูอัตราจ้าง", gradeLevel: "อ.1" },
  { fullName: "นางสาวสยุมพร มูลสาร", position: "ครูชำนาญการ", gradeLevel: "อ.1" },
  { fullName: "นางณงนิตย์ ศรีเคลือบ", position: "ครูอัตราจ้าง", gradeLevel: "อ.1" },
  { fullName: "นางสาวสุมาลิน วรรณวงค์", position: "ครูชำนาญการ", gradeLevel: "อ.1" },
  { fullName: "นางสาวพัณณิตา เจริษราษฎร์", position: "ครูอัตราจ้าง", gradeLevel: "อ.1" },
  { fullName: "นางสาวศิรประภา ธเนศมณีโรจน์", position: "ครู", gradeLevel: "อ.1" },
  { fullName: "นางสุรชัย เชื้อท้าว", position: "ครูอัตราจ้าง", gradeLevel: "อ.1" },
  { fullName: "นางสาวอริสา ปัจศรี", position: "ครูชำนาญการ", gradeLevel: "อ.1" },
  { fullName: "นางสาวปภัทรพร งามสาย", position: "ครูอัตราจ้าง", gradeLevel: "อ.1" },

  // 3. อนุบาลปีที่ 2
  { fullName: "นางสุรดา เรืองนิติธร", position: "ครูชำนาญการพิเศษ", gradeLevel: "อ.2" },
  { fullName: "นางสาวสุนี รุ่งรัศมี", position: "ครูอัตราจ้าง", gradeLevel: "อ.2" },
  { fullName: "นางสาวภัคจิรา สิงห์การ", position: "ครูชำนาญการ", gradeLevel: "อ.2" },
  { fullName: "นางประยูร พิมสิงห์", position: "ครูอัตราจ้าง", gradeLevel: "อ.2" },
  { fullName: "นางนิภาพร สมปาน", position: "ครูชำนาญการพิเศษ", gradeLevel: "อ.2" },
  { fullName: "นางสาวพนัชฌา แสวงผล", position: "ครูอัตราจ้าง", gradeLevel: "อ.2" },
  { fullName: "นางสาวบุษบา เหล่าโก้ก", position: "ครูชำนาญการพิเศษ", gradeLevel: "อ.2" },
  { fullName: "นางสาวศุภวรรณ อินทร์หอม", position: "ครูอัตราจ้าง", gradeLevel: "อ.2" },
  { fullName: "นางสาวกรทิพย์ ศกุนตานุรักษ์", position: "ครูชำนาญการพิเศษ", gradeLevel: "อ.2" },
  { fullName: "นางสาวชลลดา มลาวาสน์", position: "ครูอัตราจ้าง", gradeLevel: "อ.2" },
  { fullName: "นางสาวนิฐิมา ไชยเดช", position: "ครูชำนาญการ", gradeLevel: "อ.2" },
  { fullName: "นางสาววราภรณ์ แว่นแคว้น", position: "ครูอัตราจ้าง", gradeLevel: "อ.2" },
  { fullName: "นางสาวพัชรา ทองสวัสดิ์", position: "ครูชำนาญการพิเศษ", gradeLevel: "อ.2" },
  { fullName: "นางสาวสุภาวดี พงษ์อนันต์", position: "ครูอัตราจ้าง", gradeLevel: "อ.2" },
  { fullName: "นางอาทิตยา รักษาคุณ", position: "ครูชำนาญการ", gradeLevel: "อ.2" },
  { fullName: "นางสาวปรมาภรณ์ มานะบุตร", position: "ครูอัตราจ้าง", gradeLevel: "อ.2" },

  // 4. อนุบาลปีที่ 3
  { fullName: "นางกัลยา ธรรมสัตย์", position: "ครูชำนาญการพิเศษ", gradeLevel: "อ.3" },
  { fullName: "นางสาวเพ็ญประภา ทะคำสอน", position: "ครูอัตราจ้าง", gradeLevel: "อ.3" },
  { fullName: "นางมัลลิกา บุญครอง", position: "ครูชำนาญการ", gradeLevel: "อ.3" },
  { fullName: "นางสาวปรางแก้ว พิมพ์พวง", position: "ครูอัตราจ้าง", gradeLevel: "อ.3" },
  { fullName: "นางนภาพร เชื้อสิงห์", position: "ครูชำนาญการพิเศษ", gradeLevel: "อ.3" },
  { fullName: "นางสาวสุดารัตน์ แสงใส", position: "ครูอัตราจ้าง", gradeLevel: "อ.3" },
  { fullName: "นางสุพัตรา ลีละประสพโชค", position: "ครูชำนาญการพิเศษ", gradeLevel: "อ.3" },
  { fullName: "นางสาวขวัญชีวา โยธี", position: "ครูอัตราจ้าง", gradeLevel: "อ.3" },
  { fullName: "นางมยุรี ผาสุข", position: "ครูชำนาญการพิเศษ", gradeLevel: "อ.3" },
  { fullName: "นางสาวปราณี พุทธิวงศ์", position: "ครูอัตราจ้าง", gradeLevel: "อ.3" },
  { fullName: "นางไพรัช เสาเวียง", position: "ครูชำนาญการพิเศษ", gradeLevel: "อ.3" },
  { fullName: "นางสาวสุรางคณา สำรองพันธ์", position: "ครูอัตราจ้าง", gradeLevel: "อ.3" },
  { fullName: "นางสาวพัชราภรณ์ มุ่งสิน", position: "ครูชำนาญการพิเศษ", gradeLevel: "อ.3" },
  { fullName: "นางสาวประภาสิริ มิรัตนไพร", position: "ครูอัตราจ้าง", gradeLevel: "อ.3" },
  { fullName: "นางถุงเงิน ชำนาญกิจ", position: "ครูชำนาญการพิเศษ", gradeLevel: "อ.3" },
  { fullName: "นางวนิดา ปัจจุโส", position: "ครูอัตราจ้าง", gradeLevel: "อ.3" },

  // 5. ประถมศึกษาปีที่ 1
  { fullName: "นางบุณฑริกา ศุภลักษณ์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.1" },
  { fullName: "Mr.John Joshua Mariano", position: "ครูชาวต่างชาติ", gradeLevel: "ป.1" },
  { fullName: "นางนภาพร พุ่มจันทร์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.1" },
  { fullName: "นางณิชาภา พลเดช", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.1" },
  { fullName: "นางจิรชยา หลงชิณ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.1" },
  { fullName: "นายเศรษฐศาสตร์ สิงห์ตา", position: "ครูอัตราจ้าง", gradeLevel: "ป.1" },
  { fullName: "นางจิดาภา ป้อมภิทักษ์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.1" },
  { fullName: "นางประภากร ทัดเทียม", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.1" },
  { fullName: "นางนันท์นภัส เจริญมิตรสกุล", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.1" },
  { fullName: "นางเรวดี จันดอนแดง", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.1" },
  { fullName: "นางกชรัตน์ จันทร์งาม", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.1" },
  { fullName: "นางนิรมล เนื้ออ่อน", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.1" },
  { fullName: "นางสาวสโรชา ลารบุตร", position: "ครูผู้ช่วย", gradeLevel: "ป.1" },
  { fullName: "นางนิภาพร จารุกมล", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.1" },
  { fullName: "นางปรวรรณ สีสังข์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.1" },
  { fullName: "นางธนภรณ์ สำเภานนท์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.1" },

  // 6. ประถมศึกษาปีที่ 2
  { fullName: "นางวัชราภรณ์ สุตะพรหม", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.2" },
  { fullName: "นางนพรัตน์ ศรีอุดร", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.2" },
  { fullName: "นางสาวธัญญรัตน์ ศุภธนพิพัฒน์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.2" },
  { fullName: "นายปณิธาน พละวงศ์", position: "ครูชำนาญการ", gradeLevel: "ป.2" },
  { fullName: "นางธันย์ฉมา รฐาสุขธเนศหิรัญ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.2" },
  { fullName: "นางปิติมา อุ่มพิมาย", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.2" },
  { fullName: "นายช่วงวิทย์ ปัทมะ", position: "ครูอัตราจ้าง", gradeLevel: "ป.2" },
  { fullName: "นางจริยา กองสุข", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.2" },
  { fullName: "นางสิรินรดา สุภักดี", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.2" },
  { fullName: "นางขนิษฐา นิตย์สุวรรณ์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.2" },
  { fullName: "นางกันย์จีรา ศุภเศรษฐชาติ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.2" },
  { fullName: "Miss. Joan May Sacay", position: "ครูชาวต่างชาติ", gradeLevel: "ป.2" },
  { fullName: "นางตติยาภรณ์ สุขสว่าง", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.2" },
  { fullName: "นางนิษฐารัชต์ ภัทร์สินธัญพร", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.2" },
  { fullName: "นางสาวอุษณีย์ ภารการ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.2" },
  { fullName: "นายอัญวุฒิ คุ้มภัย", position: "ครูอัตราจ้าง", gradeLevel: "ป.2" },

  // 7. ประถมศึกษาปีที่ 3
  { fullName: "นางวิภา เขียนนอก", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.3" },
  { fullName: "นางสาวรัตนา การงาน", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.3" },
  { fullName: "นางสาวณัฐทกาญจน์ ขันอาสา", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.3" },
  { fullName: "Mrs. Kenile Khing", position: "ครูชาวต่างชาติ", gradeLevel: "ป.3" },
  { fullName: "นายปิยะนันท์ ค่ำคูณ", position: "ครูชำนาญการ", gradeLevel: "ป.3" },
  { fullName: "นางปริษา สมบูรณ์", position: "ครูชำนาญการ", gradeLevel: "ป.3" },
  { fullName: "นายธีรภัทร อร่ามโชติ", position: "ครูชำนาญการ", gradeLevel: "ป.3" },
  { fullName: "นางปิยะภา ศรีจันทร์อ่อน", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.3" },
  { fullName: "นางสายสมร เส้นทอง", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.3" },
  { fullName: "นางสาวศศิกานต์ หมายสุข", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.3" },
  { fullName: "นางจิราพันธ์ โหราย์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.3" },
  { fullName: "นางสาวปราณี สุวรรณโค", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.3" },
  { fullName: "นางรัชนีกร สุพรรณโรจน์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.3" },
  { fullName: "นายณัฐพล สมบัติ", position: "ครูชำนาญการ", gradeLevel: "ป.3" },

  // 8. ประถมศึกษาปีที่ 4
  { fullName: "นางสุมลมาลย์ เอติรัตนะ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.4" },
  { fullName: "นายณัฐพล ไชยเพชร", position: "ครูอัตราจ้าง", gradeLevel: "ป.4" },
  { fullName: "นางพรทิพย์ ดวงมาลา", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.4" },
  { fullName: "นางสาวนิภาพร วงศ์ฟองทอง", position: "ครูชำนาญการ", gradeLevel: "ป.4" },
  { fullName: "นางทิพวรรณ คำยนต์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.4" },
  { fullName: "นางสาวชฎาพร ภาระสุข", position: "ครูอัตราจ้าง", gradeLevel: "ป.4" },
  { fullName: "นางอุไร จิตรมาศ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.4" },
  { fullName: "นางสาวปทุมทอง สารการ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.4" },
  { fullName: "นางสาวมนฑการต์ ดาบพระทิตย์", position: "ครูชำนาญการ", gradeLevel: "ป.4" },
  { fullName: "นางวิไลทอง สายเบาะ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.4" },
  { fullName: "นางภัทรดาภา พระอารักษ์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.4" },
  { fullName: "Mr. Ramund Marzan Cariaga", position: "ครูชาวต่างชาติ", gradeLevel: "ป.4" },
  { fullName: "นางช้องรัตน์ สุบรรณพงษ์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.4" },
  { fullName: "นางฉวีวรรณ สุขสาร", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.4" },
  { fullName: "นางพรพิมล จิตรมาศ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.4" },

  // 9. ประถมศึกษาปีที่ 5
  { fullName: "นายฉัตรชัย บัวหลวง", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.5" },
  { fullName: "นางสาวฐิติพร ภูมิการีย์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.5" },
  { fullName: "นายธีรพล ขยายวงษ์", position: "ครูชำนาญการ", gradeLevel: "ป.5" },
  { fullName: "นายเรืองวิชญ์ แก้วพรหม", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.5" },
  { fullName: "นางมั่นใจ ผิวงาม", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.5" },
  { fullName: "นางชาณิภา พุฒพันธ์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.5" },
  { fullName: "นางศกุนตลา บัวหลวง", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.5" },
  { fullName: "นางสาวพิมลพรรณ อาษานอก", position: "ครู", gradeLevel: "ป.5" },
  { fullName: "นางสาววิไลวรรณ สมบูรณ์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.5" },
  { fullName: "นางรัชนี มูลป้อม", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.5" },
  { fullName: "นางสาวพรพิลัย ทำบุญ", position: "ครู", gradeLevel: "ป.5" },
  { fullName: "นางนุชศรา ไชยสัจ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.5" },
  { fullName: "นายอภิวัฒน์ สุมาลี", position: "ครูชำนาญการ", gradeLevel: "ป.5" },
  { fullName: "นางอุไร รุ่งเรือง", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.5" },
  { fullName: "Mr. Harold June Bolong Punay", position: "ครูชาวต่างชาติ", gradeLevel: "ป.5" },

  // 10. ประถมศึกษาปีที่ 6
  { fullName: "นางชนิสรา ศรีถาการ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.6" },
  { fullName: "นางพัชนีย์ โคตรบุรี", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.6" },
  { fullName: "Mr.Remus Amparado Palay", position: "ครูชาวต่างชาติ", gradeLevel: "ป.6" },
  { fullName: "นางฐิติภา ปิ่นโต", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.6" },
  { fullName: "นายสุทธิ พิริยะธนาพงศ์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.6" },
  { fullName: "นายวินัย อิ่นคำ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.6" },
  { fullName: "นางสาวอรอุมา อุ่นท้าว", position: "ครูชำนาญการ", gradeLevel: "ป.6" },
  { fullName: "นายณัฐวุฒิ ต้นจันทร์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.6" },
  { fullName: "นายภานุพันธ์ สุดไชย", position: "ครูชำนาญการ", gradeLevel: "ป.6" },
  { fullName: "นางสมถวิล เชสูงเนิน", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.6" },
  { fullName: "นางอมรรัตน์ ศรีพานิช", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.6" },
  { fullName: "นายชนินทร์ เมืองเหนือ", position: "ครูชำนาญการ", gradeLevel: "ป.6" },
  { fullName: "นางวรางคณา กาศักดิ์", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.6" },
  { fullName: "นายวิจิตรศิลป์ คำผาสุข", position: "ครูชำนาญการพิเศษ", gradeLevel: "ป.6" },

  // 11. ห้องเรียนพิเศษคณิตศาสตร์และวิทยาศาสตร์ (AP)
  { fullName: "นางสาวชิดชนก สระสงคราม", position: "ครู", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางสาวกานต์กนิษฐ์ จัยวัฒน์", position: "ครูชำนาญการ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นายสมชัย จารุจิตร", position: "ครูชำนาญการพิเศษ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางสาวชฎาพร บุตรสง่า", position: "ครูชำนาญการ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางสุวคนธ์ ทองพุ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นายพงศธร ชาวตะโปน", position: "ครูอัตราจ้าง", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นายวิฑูรย์ หมทอง", position: "ครูชำนาญการพิเศษ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางวะรากร ยางงาม", position: "ครูชำนาญการพิเศษ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางอารยา กัณหา", position: "ครูชำนาญการพิเศษ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "Miss Mia Annette S.Arazo", position: "ครูชาวต่างชาติ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางสาววิไลลักษณ์ บุญเต็ม", position: "ครูชำนาญการพิเศษ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางสาวนชิชา ระฎาห์", position: "ครูอัตราจ้าง", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางสาวอิศราภรณ์ ประเสริฐศรี", position: "ครูชำนาญการ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางสาวทิพาพร สังฆมโนเวศ", position: "ครูอัตราจ้าง", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางทิพย์วัลย์ แก้วพรหม", position: "ครูชำนาญการพิเศษ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางสาวกนกวรรณ ภูมพงศ์", position: "ครูอัตราจ้าง", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นายพงค์เทพ จารุกมล", position: "ครูชำนาญการพิเศษ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางสาวน้ำฝน โพธิ์สุวรรณ", position: "ครูอัตราจ้าง", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นายสุริยา ศรีคราม", position: "ครูชำนาญการพิเศษ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "Mr. Zeus Amican Longcayana", position: "ครูชาวต่างชาติ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางขวัญหทัย สมัครคุณ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางพิชญา หมทอง", position: "ครูชำนาญการพิเศษ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางจงจิตร โทนุการ", position: "ครูชำนาญการพิเศษ", gradeLevel: "ห้องเรียนพิเศษ AP" },
  { fullName: "นางสาวฟาริดา โหราศาสตร์", position: "ครูชำนาญการ", gradeLevel: "ห้องเรียนพิเศษ AP" },

  // 12. English Program (EP)
  { fullName: "นางสาวณัฏยา ศรีภา", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "Miss Dayrest La-anan Bucayan", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางวราภรณ์ ธานี", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวพิชยา เหล่าบุตรสา", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "นางทัศนะวรรณ จันทร์ลุน", position: "ครูชำนาญการ", gradeLevel: "English Program (EP)" },
  { fullName: "Mrs.Lilnabeth Panizales Sausa", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวจุฑารัตน์ หมื่นพรม", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวปภัชญา ศรีสิงห์", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "นางสว่างจิตร เทพภักดี", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "Miss MA. Algi May Chiquito De Guzman", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวนันธิญา จักร์ได้", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาววราภรณ์ จวนสาง", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวชิดตาพรรณ มูลสุวรรณ", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "Miss Gladys Meer Sarno Benasahan", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวสิริมนต์ ทวีสิทธิ์", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวอินทุอร ศรไชย", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "นายประสิทธิ์ พุฒพิภักดิ์", position: "พนักงานราชการ", gradeLevel: "English Program (EP)" },
  { fullName: "Mr.Guariz Pagunsan Suasa", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวนภาพร เรือนเจริญ", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "ว่าที่ ร.ต.หญิงจารุภา ลดาดกจิรานนท์", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "Miss Jennifer Salutin Pabilona", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวณัฐณิชา วายะลุน", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวนุสรา บุตรภักดี", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวสุพัฒตา บัวหอม", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวจิรนันท์ สุขเมือง", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Mr.Ajulo Kent", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาววิภาวี ประสานสอน", position: "ครูชำนาญการ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวพิชญานิน เรืองจันทร์", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Miss Tajinder Kaur", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางรัตนากร ประสานสิงห์", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวพัดชา สุขพอดี", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Mr.Alistair Gilbert Macpherson", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางธิดาภรณ์ ทินบุตร", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวถิรมน สิงหาภักดิ์", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Mr.Paul David James", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวพินทร์ณัชชา แก้วกนก", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวศศิกานต์ วิลัยเลิศ", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Mr.Michael Edward Baxter", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวเบญจพร รีพล", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวเบญจมาศ ภูพิทักษ์", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Miss Bwenyenle Kent", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวกนกพิชญ์ บุญดาว", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวณัฏฐณิชา บุตรดา", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Mr.Stephen Brown", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นายศุภโชค สาระบุตร", position: "ครูชำนาญการ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวศุภรดา มุ่งหมาย", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Mr.Jeston Delos Santos Cannete", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวพนิดา คงสำรวย", position: "ครูชำนาญการ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวนัทธ์พิรดา บัวพันธ์", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Miss Tesinle khing", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวทรรณพร บุญศรี", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวณฉัตร สุภาณดี", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Mr.Chaster Anthony", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นายเอกชัย ประสานสิงห์", position: "ครูชำนาญการ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวศิริพรรณ ยังมงคล", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Mrs.Evangeline Labrador Rosario", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "ว่าที่ ร.ต.สัจจวัฒน์ ศรีชัย", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวกนกวรรณ ทิพย์อาสน์", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Miss Naing Mya Mon", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นายธนัฏดนัย ธนมนต์ศิริ", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวปาริชาติ ชะฎา", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Miss Jenelyn Fernandez", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางเสาวณีย์ ดอกดวง", position: "ครูชำนาญการพิเศษ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวนัขชมณย์ บุญพุฒ", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Mr.Craig Suwich Sanwong", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นายพันธกานต์ ชูพูล", position: "ครู (ครูใหม่)", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวสุรักษา ดวงไข", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Mrs.Arlene A.Tilla-In", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวคนึงนิตย์ สวัสดิ์พงษ์", position: "ครู", gradeLevel: "English Program (EP)" },
  { fullName: "นางสาวณัฐฐิรา สิมานุรักษ์", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
  { fullName: "Mr. Jan Erik Mikael Karlsson", position: "ครูชาวต่างชาติ", gradeLevel: "English Program (EP)" },
  { fullName: "นางพชรวรรณ บุญศิริ", position: "ครูชำนาญการ", gradeLevel: "English Program (EP)" },
  { fullName: "นายศาศวัฒก์ กาศักดิ์", position: "ครูอัตราจ้าง", gradeLevel: "English Program (EP)" },
];
